import "~/styles/globals.css"

import type { Metadata } from "next"
import { JetBrains_Mono } from "next/font/google"
import { cookies } from "next/headers"
import type * as React from "react"
import Navbar from "~/components/Navbar"
import { ThemeProvider } from "~/components/ThemeProvider"
import { Toaster } from "~/components/ui/toaster"
import { AuthProvider } from "~/server/AuthContext"
import { validateRequest } from "~/server/auth"
import { TRPCReactProvider } from "~/trpc/react"

const jetbrains = JetBrains_Mono({
	subsets: ["latin"],
	weight: "600"
})

export const metadata: Metadata = {
	title: "CarbonCraft",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }]
}

export default async function RootLayout({
	children
}: Readonly<{ children: React.ReactNode }>) {
	const session = await validateRequest()

	return (
		<html lang="en" className={`${jetbrains.className}`}>
			<body>
				<AuthProvider value={session}>
					<TRPCReactProvider cookies={cookies().toString()}>
						<ThemeProvider
							attribute="class"
							defaultTheme="dark"
							enableSystem
							disableTransitionOnChange
						>
							<main>
								<Navbar session={session.session} />
								{children}
							</main>
							<Toaster />
						</ThemeProvider>
					</TRPCReactProvider>
				</AuthProvider>
			</body>
		</html>
	)
}
